# Generated by Django 4.2.30 on 2026-05-26 19:35

from django.db import migrations, models


def copy_owner_to_audit_fields(apps, schema_editor):
    for model_name in ('Address', 'Order', 'Warehouse', 'Shipment', 'BulkBatch'):
        model = apps.get_model('logistics', model_name)
        for row in model.objects.exclude(owner_id__isnull=True).iterator():
            updates = {}
            if not row.created_by_id:
                updates['created_by_id'] = row.owner_id
            if not row.updated_by_id:
                updates['updated_by_id'] = row.owner_id
            if updates:
                model.objects.filter(pk=row.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_basemodel_audit_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_number_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='shipment',
            name='unique_shipment_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='unique_warehouse_code_per_owner',
        ),
        migrations.RunPython(copy_owner_to_audit_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bulkbatch',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('created_by', 'order_number'), name='unique_order_number_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('created_by', 'internal_order_id'), name='unique_shipment_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('created_by', 'code'), name='unique_warehouse_code_per_creator'),
        ),
    ]
