# Generated by Django 4.2.30 on 2026-05-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_shipment_order_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='drop_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shipment',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shipment',
            name='parcels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on delivery')], default='PREPAID', max_length=32),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address',
            field=models.JSONField(default=dict),
        ),
    ]
