# Generated by Django 4.2.30 on 2026-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_shipment_cod_amount_shipment_drop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_label',
            field=models.TextField(blank=True),
        ),
    ]
