# Generated by Django 4.2.30 on 2026-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shipment_shipping_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MANIFESTED', 'Manifested'), ('BOOKED', 'Booked'), ('PICKED_UP', 'Picked up'), ('PICKED_DONE', 'Picked done'), ('IN_TRANSIT', 'In transit'), ('TRANSIT', 'Transit'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MANIFESTED', 'Manifested'), ('BOOKED', 'Booked'), ('PICKED_UP', 'Picked up'), ('PICKED_DONE', 'Picked done'), ('IN_TRANSIT', 'In transit'), ('TRANSIT', 'Transit'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], max_length=32),
        ),
    ]
