# Generated by Django 4.2.30 on 2026-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_shipment_status_alter_trackingevent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='normalized_payload',
        ),
    ]
