# Generated by Django 4.2.30 on 2026-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_remove_shipment_normalized_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbatch',
            name='order_list',
            field=models.JSONField(default=list),
        ),
    ]
