# Generated by Django 4.2.30 on 2026-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_bulkbatch_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbatch',
            name='request_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bulkbatch',
            name='response_payload',
            field=models.JSONField(default=dict),
        ),
    ]
