# Generated by Django 4.2.30 on 2026-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_bulkbatch_request_payload_bulkbatch_response_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkbatch',
            name='request_payload',
        ),
        migrations.RemoveField(
            model_name='bulkbatch',
            name='response_payload',
        ),
        migrations.RemoveField(
            model_name='bulkorderresult',
            name='shipment',
        ),
        migrations.AddField(
            model_name='bulkorderresult',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
