# Generated by Django 4.2.30 on 2026-05-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_remove_bulkbatch_request_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='bulk_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.bulkbatch'),
        ),
    ]
