# Generated by Django 4.2.30 on 2026-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_shipment_bulk_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorderresult',
            name='internal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
